### ISSUE TITLE
Support new field of Context model

### ISSUE THREAD

**Issue by blvp** [Hydrospheredata/mist-cli#19]
Mist v1.0.0-RC16 has `max-conn-failure` setting in Context definition which is missing in cli

**Comment by dos65** [comment]
Could we change this behavior of building request body into a more flexible way where every field from `data` section is putting into body automatically?
I'm going to add more settings for contexts in the next versions and can't use them from mist-cli during development.

**Comment by blvp** [comment]
Yes, for sure. But it's only required for context. Need to test it with mist how it will handle the unknown fields and some missing fields.
